# Tarefas Módulo 5
- Nome: Cícero Henrique dos Santos
- Data: 17/02/2022

In [20]:
import numpy as np
import pandas as pd

Considere os arrays numpy X, y abaixo:

In [21]:
from sklearn.datasets import load_iris

X = load_iris().data
y = load_iris().target

In [22]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [23]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

------
### Exercício 1: 
Crie um dataframe df do pandas a partir de X, y.

Primeiro, concatene os arrays numpy. Na sequência transforme o array final para um dataframe. Altere o nome das colunas para 'X1', 'X2', 'X3', 'X4' e 'target'.

In [24]:
#Concatenando os arrays
array_concat = np.c_[X,y]

array_concat

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [25]:
#Criando DataFrame
df_array = pd.DataFrame(array_concat)
df_array

0    1    2    3    4
0    5.1  3.5  1.4  0.2  0.0
1    4.9  3.0  1.4  0.2  0.0
2    4.7  3.2  1.3  0.2  0.0
3    4.6  3.1  1.5  0.2  0.0
4    5.0  3.6  1.4  0.2  0.0
..   ...  ...  ...  ...  ...
145  6.7  3.0  5.2  2.3  2.0
146  6.3  2.5  5.0  1.9  2.0
147  6.5  3.0  5.2  2.0  2.0
148  6.2  3.4  5.4  2.3  2.0
149  5.9  3.0  5.1  1.8  2.0

[150 rows x 5 columns]

In [26]:
#renomeando as colunas
df_array.rename(columns={0:"X1", 
                         1:"X2", 
                         2:"X3", 
                         3:"X4", 
                         4:"target"},
                inplace=True)
df_array

X1   X2   X3   X4  target
0    5.1  3.5  1.4  0.2     0.0
1    4.9  3.0  1.4  0.2     0.0
2    4.7  3.2  1.3  0.2     0.0
3    4.6  3.1  1.5  0.2     0.0
4    5.0  3.6  1.4  0.2     0.0
..   ...  ...  ...  ...     ...
145  6.7  3.0  5.2  2.3     2.0
146  6.3  2.5  5.0  1.9     2.0
147  6.5  3.0  5.2  2.0     2.0
148  6.2  3.4  5.4  2.3     2.0
149  5.9  3.0  5.1  1.8     2.0

[150 rows x 5 columns]

------
### Exercício 2: 
Usando o df criado no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [27]:
#Calculando a média da variável X2 para cada valor de target
df_array.groupby(by = "target").apply(lambda x: x.X2.mean())

target
0.0    3.428
1.0    2.770
2.0    2.974
dtype: float64

------
### Exercício 3: 
Construa um dicionário mapeando os valores:
        
        0 - 'A'
        
        1 - 'B'
        
        2 - 'C'
        
Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.

In [28]:
#Criando dicionário
dicionario = {0:"A",
              1:"B",
              2:"C"}
#Inserindo uma nova coluna target_2 com valores adicionados mapeando cada linha da coluna target
df_array.insert(5,
                "target_2",
                df_array.target.map(dicionario),True)

df_array

X1   X2   X3   X4  target target_2
0    5.1  3.5  1.4  0.2     0.0        A
1    4.9  3.0  1.4  0.2     0.0        A
2    4.7  3.2  1.3  0.2     0.0        A
3    4.6  3.1  1.5  0.2     0.0        A
4    5.0  3.6  1.4  0.2     0.0        A
..   ...  ...  ...  ...     ...      ...
145  6.7  3.0  5.2  2.3     2.0        C
146  6.3  2.5  5.0  1.9     2.0        C
147  6.5  3.0  5.2  2.0     2.0        C
148  6.2  3.4  5.4  2.3     2.0        C
149  5.9  3.0  5.1  1.8     2.0        C

[150 rows x 6 columns]

------
### Exercício 4:

4.1: Filtre o dataframe df onde X1 é maior do que 6 __ou__ target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula;

In [29]:
#Filtrando dataframe onde X1 é maior do que 6 ou target é diferente de 2
df1 = df_array[(df_array.X1 > 6) | (df_array.target != 2)] 
df1

X1   X2   X3   X4  target target_2
0    5.1  3.5  1.4  0.2     0.0        A
1    4.9  3.0  1.4  0.2     0.0        A
2    4.7  3.2  1.3  0.2     0.0        A
3    4.6  3.1  1.5  0.2     0.0        A
4    5.0  3.6  1.4  0.2     0.0        A
..   ...  ...  ...  ...     ...      ...
144  6.7  3.3  5.7  2.5     2.0        C
145  6.7  3.0  5.2  2.3     2.0        C
146  6.3  2.5  5.0  1.9     2.0        C
147  6.5  3.0  5.2  2.0     2.0        C
148  6.2  3.4  5.4  2.3     2.0        C

[141 rows x 6 columns]

4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2;

In [30]:
#Salvando apenas os primeiros 15 índices em um novo dataframe
df2 = df1.iloc[:15]
df2

X1   X2   X3   X4  target target_2
0   5.1  3.5  1.4  0.2     0.0        A
1   4.9  3.0  1.4  0.2     0.0        A
2   4.7  3.2  1.3  0.2     0.0        A
3   4.6  3.1  1.5  0.2     0.0        A
4   5.0  3.6  1.4  0.2     0.0        A
5   5.4  3.9  1.7  0.4     0.0        A
6   4.6  3.4  1.4  0.3     0.0        A
7   5.0  3.4  1.5  0.2     0.0        A
8   4.4  2.9  1.4  0.2     0.0        A
9   4.9  3.1  1.5  0.1     0.0        A
10  5.4  3.7  1.5  0.2     0.0        A
11  4.8  3.4  1.6  0.2     0.0        A
12  4.8  3.0  1.4  0.1     0.0        A
13  4.3  3.0  1.1  0.1     0.0        A
14  5.8  4.0  1.2  0.2     0.0        A

4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.

In [31]:
#Deletando as colunas target e target_2 do dataframe df1
df1 = df1.drop(["target","target_2"], axis=1)
df1.values

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [32]:
#Deletando as colunas target e target_2 do dataframe df2
df2 = df2.drop(["target","target_2"], axis=1)
df2.values

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2]])

In [33]:
#Imprimindo o resultado da multiplicação do df1 X a tranporta do df2
resultado_mult_transport = (df1 * df2.T)
resultado_mult_transport

X1  X2  X3  X4   0   1   2   3   4   5   6   7   8   9  10  11  12  13  \
0   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
1   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
2   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
3   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
4   NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
148 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
X1  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
X2  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
X3  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   
X4  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN   

     14  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN  
..   ..  
148 NaN  
X1  NaN  
X2  NaN  
X3  NaN  
X4  NaN  

[145 rows x 19 columns]

------
### Exercício 5:

5.1: Crie uma função que receba um  número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays;

In [84]:
#Exercício 5.1

def listar_numeros(x):
    numero = int(x)
    lista = []
    for elemento in range(0,numero+1,1):
        lista.append(elemento)
    return print(lista)

listar_numeros(9)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição;

In [139]:
def lista_aleatoria(list):
    numeros_aleatorios = []
    numeros_aleatorios = np.random.choice(list, size=np.size(list), replace=False)
    return print(numeros_aleatorios)

numeros = [0,1,3,7,45,67]
lista_aleatoria(numeros)

[67 45  0  1  3  7]


5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números

In [96]:
def lista_inteiros(x):
    numero = int(x)
    numeros_inteiros = []
    for elemento in range(0, numero):
        numeros_inteiros.append(np.random.randint(1, numero))
    return print(numeros_inteiros)

lista_inteiros(10)

[8, 8, 5, 8, 7, 3, 3, 7, 5, 1]


------
### Exercício 6: 
Construa uma função divide_dados:
        
- recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
- divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays, X1 e X2, onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
- interpretando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X; enquanto X2 deve ser o resto.
- retorne esses dois arrays.
        
       

In [165]:
def divide_dados(list, p):
    matriz = np.array_split(list, p)
    print(matriz)
    X1 = matriz[0]
    X2 = matriz[1]
    return print(X1, X2)

lista_numeros = [[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]

divide_dados(lista_numeros,2)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]
[[1 2 3 4 5]] [[ 6  7  8  9 10]]
